language: ruby

install:
  - bundle install --path vendor/bundle
  - npm install

script:
  - npm run build:js
  - JEKYLL_ENV=production bundle exec jekyll build

deploy:
  skip_cleanup: true
  provider: s3
  access_key_id: AKIAI5LSKG333LXV7TRA
  secret_access_key:
    secure: YaRSuGYEE+hBq7s3GQ/tPUzDAgUuSEsCHedfJG1uJu+t03c6zjMxAjYVuiT2XpJGqZZ3PURKu4EcZht2wHKR0kwMpx0+/yZzkKIb8JqfRmUl+tVeKpRqxCsEqScWLzj8J5gdjPV1tHn4zIzn7efgBDlIunI/mbdiH4iw82PWStFy8dTsKGk9UCESflpVIPBfnLrLLpZQRkuOBKPv67DnCavqz8w5E+wnkSq+vtFm1xT/5us97l+aFNR6AumrrpydwNAyaTkUf4ZheYYDr+xG01ATwoY3qRqUZAtL+O0qShIXxALy8s3drJxAJCgE91nfSeNBjMQslqtWODUdeSKn6BVHCHytiPMPhvhkTgvM0dzpLr9xqFlmHleI7oqt1t0usmfS9gkyJCtf26602RSSXfl6qyJ9waeMZRVp9I4/EbD/e77QcqQvVICKcRSPHHmf9RqXnfFXfDNEGpSEBrer40jkvc5WOWgk42ygCMNGrNiVHRTCkMFlCplD1pkmK6E5/SBbc0NVu0+XnPYIcVV6xC+tzgZPRgg1E4YwIX4nXRoqMhxRH8ioMjfNIM3+O2yi2K58UWVfSsKU/tBRcJO1tSwC+Jh9AaPbPGzAmzIXWNaq4WqcvUYgbRuJ2sMa75wLutDtJK30s5F+LeESLbU1FkZ6Z4AVVh017UuakHGGznQ=
  bucket: s3://knightoftheoldcode.com 
  local-dir: _site
  acl: public_read
  on:
    repo: knightoftheoldcode/knightoftheoldcode.com
